{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 1,
  "build_id": "v0.98.2",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_OYSTER",
                "title": {
                  "key": "NUTRITIOUS_OYSTER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECISE_SCISSORS",
                "title": {
                  "key": "PRECISE_SCISSORS.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "LEAFY_POULTICE",
                "title": {
                  "key": "LEAFY_POULTICE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 99,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PRECISE_SCISSORS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 75,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.PRECISE_SCISSORS",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "NUTRITIOUS_OYSTER",
                "title": {
                  "key": "NUTRITIOUS_OYSTER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LEAFY_POULTICE",
                "title": {
                  "key": "LEAFY_POULTICE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REANIMATE"
              }
            ],
            "current_gold": 99,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 66,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "POMANDER",
                "title": {
                  "key": "POMANDER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              }
            ],
            "current_gold": 99,
            "current_hp": 57,
            "damage_taken": 13,
            "event_choices": [
              {
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 70,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.PRECARIOUS_SHEARS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.QUASAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 116,
            "current_hp": 71,
            "damage_taken": 4,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.BORROWED_TIME"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DANSE_MACABRE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BORROWED_TIME"
              }
            ],
            "current_gold": 110,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACCURACY"
                },
                "was_picked": false
              }
            ],
            "current_gold": 114,
            "current_hp": 56,
            "damage_taken": 1,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.GAMMA_BLAST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 3,
                "id": "CARD.GAMMA_BLAST"
              }
            ],
            "current_gold": 133,
            "current_hp": 68,
            "damage_taken": 3,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GRAVE_WARDEN"
              }
            ],
            "current_gold": 127,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.RICOCHET"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 3,
                "id": "CARD.RICOCHET"
              }
            ],
            "current_gold": 125,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 274,
            "current_hp": 50,
            "damage_taken": 18,
            "event_choices": [
              {
                "title": {
                  "key": "JUNGLE_MAZE_ADVENTURE.pages.INITIAL.options.SOLO_QUEST.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 141,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "current_gold": 268,
            "current_hp": 48,
            "damage_taken": 18,
            "event_choices": [
              {
                "title": {
                  "key": "JUNGLE_MAZE_ADVENTURE.pages.INITIAL.options.SOLO_QUEST.title",
                  "table": "events"
                },
                "variables": {
                  "SoloGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 141.727441,
                    "bool_value": false,
                    "string_value": null
                  },
                  "JoinForcesGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 59.564784,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 141,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "current_gold": 266,
            "current_hp": 38,
            "damage_taken": 18,
            "event_choices": [
              {
                "title": {
                  "key": "JUNGLE_MAZE_ADVENTURE.pages.INITIAL.options.SOLO_QUEST.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 141,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.JUNGLE_MAZE_ADVENTURE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SPECTRUM_SHIFT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ROYAL_GAMBLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.GATHER_LIGHT"
              }
            ],
            "current_gold": 288,
            "current_hp": 49,
            "damage_taken": 1,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.LEGION_OF_BONE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.AFTERLIFE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIGH_FIVE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LEGION_OF_BONE"
              }
            ],
            "current_gold": 279,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.POT_OF_GHOULS",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.BACKFLIP"
              }
            ],
            "current_gold": 285,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.LEAF_SLIME_S",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.TWIG_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 288,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.VENERATE"
            ]
          },
          {
            "current_gold": 279,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.GRAVE_WARDEN"
            ]
          },
          {
            "current_gold": 285,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.NEUTRALIZE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 347,
            "current_hp": 43,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 59,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "current_gold": 343,
            "current_hp": 42,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "笨拙"
                  }
                }
              }
            ],
            "gold_gained": 64,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "cards_gained": [
              {
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 285,
            "current_hp": 38,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.ORNATE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.AMETHYST_AUBERGINE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 347,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.GAMMA_BLAST"
            ]
          },
          {
            "current_gold": 343,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.REANIMATE"
            ]
          },
          {
            "current_gold": 285,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BACKFLIP"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 399,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 52,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.TINY_MAILBOX",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 394,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 51,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.ICE_CREAM",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 330,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.STURDY_CLAMP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 515,
            "current_hp": 36,
            "damage_taken": 7,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_STATUE.pages.INITIAL.options.DIVE_INTO_WATER.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 116,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "current_gold": 511,
            "current_hp": 35,
            "damage_taken": 7,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_STATUE.pages.INITIAL.options.DIVE_INTO_WATER.title",
                  "table": "events"
                },
                "variables": {
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "石之剑"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 7,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 117,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "current_gold": 447,
            "current_hp": 31,
            "damage_taken": 7,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_STATUE.pages.INITIAL.options.DIVE_INTO_WATER.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 117,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SUNKEN_STATUE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUPERMASSIVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ARSENAL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 528,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BONE_SHARDS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEATHS_DOOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DELAY"
                },
                "was_picked": false
              }
            ],
            "current_gold": 524,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_DOOM",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TOOLS_OF_THE_TRADE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 476,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FOGMOG_NORMAL",
            "monster_ids": [
              "MONSTER.FOGMOG"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 528,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.GATHER_LIGHT"
            ]
          },
          {
            "current_gold": 524,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BORROWED_TIME"
            ]
          },
          {
            "current_gold": 476,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PIERCING_WAIL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MONOLOGUE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 569,
            "current_hp": 34,
            "damage_taken": 2,
            "gold_gained": 41,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.THE_COURIER",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.SIC_EM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SENTRY_MODE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SIC_EM"
              }
            ],
            "current_gold": 560,
            "current_hp": 34,
            "damage_taken": 1,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 522,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 46,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYRDONIS_ELITE",
            "monster_ids": [
              "MONSTER.BYRDONIS"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.HEGEMONY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUPERMASSIVE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.HEGEMONY"
              }
            ],
            "current_gold": 583,
            "current_hp": 31,
            "damage_taken": 3,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PAGESTORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRAIN_POWER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 575,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.ESCAPE_PLAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.ESCAPE_PLAN"
              }
            ],
            "current_gold": 549,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INKLETS_NORMAL",
            "monster_ids": [
              "MONSTER.INKLET",
              "MONSTER.INKLET",
              "MONSTER.INKLET"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 583,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.HEGEMONY"
            ]
          },
          {
            "current_gold": 575,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BODYGUARD"
            ]
          },
          {
            "current_gold": 549,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PIERCING_WAIL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.GENESIS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ROYALTIES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEIRLOOM_HAMMER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.GENESIS"
              }
            ],
            "current_gold": 683,
            "current_hp": 11,
            "damage_taken": 20,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.SEANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SOUL_STORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEVOUR_LIFE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SEANCE"
              }
            ],
            "current_gold": 675,
            "current_hp": 29,
            "damage_taken": 5,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.FAN_OF_KNIVES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STORM_OF_STEEL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_HUNT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.FAN_OF_KNIVES"
              }
            ],
            "current_gold": 659,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 110,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_KIN_BOSS",
            "monster_ids": [
              "MONSTER.KIN_FOLLOWER",
              "MONSTER.KIN_FOLLOWER",
              "MONSTER.KIN_PRIEST"
            ],
            "room_type": "boss",
            "turns_taken": 14
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOASTY_MITTENS",
                "title": {
                  "key": "TOASTY_MITTENS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PUMPKIN_CANDLE",
                "title": {
                  "key": "PUMPKIN_CANDLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 683,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.YUMMY_COOKIE",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.GENESIS",
              "CARD.FALLING_STAR",
              "CARD.DEFEND_REGENT",
              "CARD.DEFEND_REGENT"
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SEAL_OF_GOLD",
                "title": {
                  "key": "SEAL_OF_GOLD.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOY_BOX",
                "title": {
                  "key": "TOY_BOX.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 675,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SEAL_OF_GOLD.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 37,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.SEAL_OF_GOLD",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "BIIIG_HUG",
                "title": {
                  "key": "BIIIG_HUG.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PUMPKIN_CANDLE",
                "title": {
                  "key": "PUMPKIN_CANDLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 659,
            "current_hp": 70,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 39,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.YUMMY_COOKIE",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.FAN_OF_KNIVES",
              "CARD.SURVIVOR",
              "CARD.RICOCHET",
              "CARD.ESCAPE_PLAN"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MANIFEST_AUTHORITY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              }
            ],
            "current_gold": 702,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.LIQUID_BRONZE"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.POKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRAIN_POWER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              }
            ],
            "current_gold": 661,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 16,
            "gold_lost": 30,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.TACTICIAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.TACTICIAN"
              }
            ],
            "current_gold": 686,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 802,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.INITIAL.options.RETURN_THE_KEY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "current_gold": 761,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.INITIAL.options.RETURN_THE_KEY.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "current_gold": 786,
            "current_hp": 70,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.INITIAL.options.RETURN_THE_KEY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LANTERN_KEY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.RESONANCE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.RESONANCE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 475,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 267,
            "gold_spent": 60,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.LAVA_LAMP",
                "was_picked": true
              }
            ]
          },
          {
            "bought_relics": [
              "RELIC.LANTERN",
              "RELIC.CANDELABRA",
              "RELIC.DOLLYS_MIRROR"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.RIGHT_HAND_HAND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCOURGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NEGATIVE_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LETHALITY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GANG_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNOCKDOWN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.SEANCE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 47,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 714,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.LUCKY_TONIC",
                "was_picked": false
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LANTERN",
                "was_picked": true
              },
              {
                "choice": "RELIC.CANDELABRA",
                "was_picked": true
              },
              {
                "choice": "RELIC.DOLLYS_MIRROR",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 20,
                  "id": "CARD.HAND_TRICK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TACTICIAN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SKEWER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 20,
                "id": "CARD.HAND_TRICK"
              },
              {
                "floor_added_to_deck": 20,
                "id": "CARD.PREPARED"
              },
              {
                "floor_added_to_deck": 20,
                "id": "CARD.BACKFLIP"
              },
              {
                "floor_added_to_deck": 20,
                "id": "CARD.FOOTWORK"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 163,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 548,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.ORRERY",
                "was_picked": true
              },
              {
                "choice": "RELIC.CHANDELIER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.RESONANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 21,
                "id": "CARD.RESONANCE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.RESONANCE"
              }
            ],
            "current_gold": 494,
            "current_hp": 72,
            "damage_taken": 3,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.INVOKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DELAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIGH_FIVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.SIC_EM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.INVOKE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.SIC_EM"
              }
            ],
            "current_gold": 36,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 25,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.FLEX_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.ESCAPE_PLAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 21,
                "id": "CARD.ESCAPE_PLAN"
              }
            ],
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 14,
                "id": "CARD.ESCAPE_PLAN"
              }
            ],
            "current_gold": 188,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 25,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 22,
                  "id": "CARD.SPECTRUM_SHIFT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 22,
                "id": "CARD.SPECTRUM_SHIFT"
              }
            ],
            "current_gold": 513,
            "current_hp": 71,
            "damage_taken": 1,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_used": [
              "POTION.BLOCK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SHROUD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BURY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIGH_FIVE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 16,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 30,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 22,
                  "id": "CARD.ESCAPE_PLAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOUNCING_FLASK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 22,
                "id": "CARD.ESCAPE_PLAN"
              }
            ],
            "current_gold": 218,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_OBSCURA_NORMAL",
            "monster_ids": [
              "MONSTER.THE_OBSCURA"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 513,
            "current_hp": 71,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.RESONANCE"
            ]
          },
          {
            "current_gold": 16,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.INVOKE"
            ]
          },
          {
            "current_gold": 218,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.FOOTWORK"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 559,
            "current_hp": 71,
            "damage_taken": 0,
            "gold_gained": 46,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.TOXIC_EGG",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 63,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 47,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.GREMLIN_HORN",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 269,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 51,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.UNCEASING_TOP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 559,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 4,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": true
              }
            ],
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 63,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SEANCE"
            ]
          },
          {
            "current_gold": 269,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PREPARED"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 26,
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 26,
                "id": "CARD.DEVASTATE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 71,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 408,
            "gold_spent": 80,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              },
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SIC_EM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DIRGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALCIFY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROLONG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAND_OF_GREED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GRAVE_WARDEN"
              }
            ],
            "current_gold": 13,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 50,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": false
              },
              {
                "choice": "RELIC.REPTILE_TRINKET",
                "was_picked": false
              },
              {
                "choice": "RELIC.CHEMICAL_X",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 26,
                  "id": "CARD.HIDDEN_DAGGERS"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 26,
                "id": "CARD.HIDDEN_DAGGERS"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 130,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 39,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 71,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DEVASTATE"
            ]
          },
          {
            "current_gold": 13,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.GRAVE_WARDEN"
            ]
          },
          {
            "current_gold": 130,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.HIDDEN_DAGGERS"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SHINING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 115,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 44,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.AMETHYST_AUBERGINE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BORROWED_TIME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ENFEEBLING_TOUCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FETCH"
                },
                "was_picked": false
              }
            ],
            "current_gold": 40,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 37,
            "gold_lost": 10,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOWLER_HAT",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.SHADOW_STEP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 28,
                "id": "CARD.SHADOW_STEP"
              }
            ],
            "current_gold": 183,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 53,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PLANISPHERE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 29,
                  "id": "CARD.ORBIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 29,
                "id": "CARD.ORBIT"
              }
            ],
            "current_gold": 143,
            "current_hp": 69,
            "damage_taken": 6,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.FIRE_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.REAP"
                },
                "was_picked": false
              }
            ],
            "current_gold": 34,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 19,
            "gold_lost": 25,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 29,
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 29,
                "id": "CARD.ACROBATICS"
              }
            ],
            "current_gold": 212,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.HUNTER_KILLER_NORMAL",
            "monster_ids": [
              "MONSTER.HUNTER_KILLER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 143,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.WEAK_POTION"
            ],
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 34,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SEANCE"
            ]
          },
          {
            "current_gold": 212,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ACROBATICS"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.SEVEN_STARS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.THE_SMITH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRASH_LANDING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.SEVEN_STARS"
              }
            ],
            "current_gold": 253,
            "current_hp": 43,
            "damage_taken": 32,
            "gold_gained": 110,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.FLEX_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.DEVOUR_LIFE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.EIDOLON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SENTRY_MODE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEVOUR_LIFE"
              }
            ],
            "current_gold": 124,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 120,
            "gold_lost": 30,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.ADRENALINE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.AFTERIMAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLADE_OF_INK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.ADRENALINE"
              }
            ],
            "current_gold": 322,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 110,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE"
            ],
            "room_type": "boss",
            "turns_taken": 11
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "CROSSBOW",
                "title": {
                  "key": "CROSSBOW.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CLAWS",
                "title": {
                  "key": "CLAWS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 253,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 32,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.SAI",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "SPIKED_GAUNTLETS",
                "title": {
                  "key": "SPIKED_GAUNTLETS.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 124,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SPIKED_GAUNTLETS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.SPIKED_GAUNTLETS",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "IRON_CLUB",
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SPIKED_GAUNTLETS",
                "title": {
                  "key": "SPIKED_GAUNTLETS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 322,
            "current_hp": 70,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.IRON_CLUB",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SUMMON_FORTH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GAMMA_BLAST"
                },
                "was_picked": false
              }
            ],
            "current_gold": 274,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 21,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.WISP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLIGHT_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPUR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 128,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 24,
            "gold_lost": 20,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 350,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.DOUBT"
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 34,
                  "id": "CARD.REFLECT"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_REGENT"
                }
              },
              {
                "final_card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 34,
                  "id": "CARD.SUMMON_FORTH"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_REGENT"
                }
              }
            ],
            "current_gold": 274,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRIAL.pages.INITIAL.options.REJECT.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TRIAL.pages.REJECT.options.ACCEPT.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TRIAL.pages.NONDESCRIPT.options.INNOCENT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "current_gold": 128,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRIAL.pages.INITIAL.options.ACCEPT.title",
                  "table": "events"
                },
                "variables": {
                  "EntrantNumber": {
                    "type": "BaseDynamic",
                    "decimal_value": 147,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TRIAL.pages.NOBLE.options.GUILTY.title",
                  "table": "events"
                },
                "variables": {
                  "EntrantNumber": {
                    "type": "BaseDynamic",
                    "decimal_value": 147,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "cards_gained": [
              {
                "id": "CARD.DOUBT"
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.OUTBREAK"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_SILENT"
                }
              },
              {
                "final_card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.INFINITE_BLADES"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_SILENT"
                }
              }
            ],
            "current_gold": 350,
            "current_hp": 70,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRIAL.pages.INITIAL.options.ACCEPT.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TRIAL.pages.NONDESCRIPT.options.INNOCENT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TRIAL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.SEVEN_STARS"
              }
            ],
            "current_gold": 274,
            "current_hp": 57,
            "damage_taken": 18,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.HOLD_ON_0.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_0.options.HOLD_ON_1.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_1.options.HOLD_ON_2.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_2.options.HOLD_ON_3.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.LEGION_OF_BONE"
              }
            ],
            "current_gold": 128,
            "current_hp": 54,
            "damage_taken": 12,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.HOLD_ON_0.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "骸骨军团"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 6,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_0.options.HOLD_ON_1.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "骸骨军团"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 6,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_1.options.HOLD_ON_2.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "骸骨军团"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 6,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "骸骨军团"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 6,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 26,
                "id": "CARD.HIDDEN_DAGGERS"
              }
            ],
            "current_gold": 350,
            "current_hp": 37,
            "damage_taken": 33,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.HOLD_ON_0.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_0.options.HOLD_ON_1.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_1.options.HOLD_ON_2.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_2.options.HOLD_ON_3.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_3.options.HOLD_ON_4.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_4.options.HOLD_ON_5.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SLIPPERY_BRIDGE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 274,
            "current_hp": 57,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BATTLEWORN_DUMMY.pages.INITIAL.options.SETTING_2.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "current_gold": 113,
            "current_hp": 54,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BATTLEWORN_DUMMY.pages.INITIAL.options.SETTING_2.title",
                  "table": "events"
                },
                "variables": {
                  "Setting1Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 270.0,
                    "bool_value": false,
                    "string_value": null
                  },
                  "Setting2Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 540.0,
                    "bool_value": false,
                    "string_value": null
                  },
                  "Setting3Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 1080.0,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 15,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "current_gold": 350,
            "current_hp": 45,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BATTLEWORN_DUMMY.pages.INITIAL.options.SETTING_2.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 8,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BATTLEWORN_DUMMY",
            "room_type": "event",
            "turns_taken": 0
          },
          {
            "model_id": "ENCOUNTER.BATTLEWORN_DUMMY_EVENT_ENCOUNTER",
            "monster_ids": [
              "MONSTER.BATTLE_FRIEND_V2"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 274,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 113,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DEVOUR_LIFE"
            ]
          },
          {
            "current_gold": 350,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ADRENALINE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 326,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 52,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 174,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 61,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.REPTILE_TRINKET",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 396,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 46,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.KUSARIGAMA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 2
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 5
                    }
                  ]
                }
              }
            ],
            "current_gold": 326,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.SKILL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.WISDOM.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 3
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 7
                    }
                  ]
                }
              }
            ],
            "current_gold": 174,
            "current_hp": 54,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.POWER.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.EXPERTISE.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 2
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 4
                    }
                  ]
                }
              }
            ],
            "current_gold": 396,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.SKILL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.ENERGIZED.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 4,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TINKER_TIME",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SWORD_SAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 379,
            "current_hp": 59,
            "damage_taken": 16,
            "gold_gained": 53,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 40,
                  "id": "CARD.PARSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MELANCHOLY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.VEILPIERCER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.PARSE"
              }
            ],
            "current_gold": 191,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 42,
            "gold_lost": 25,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HAND_TRICK"
                },
                "was_picked": false
              }
            ],
            "current_gold": 445,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 49,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.FORTIFIER",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RIPPLE_BASIN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNIGHTS_ELITE",
            "monster_ids": [
              "MONSTER.FLAIL_KNIGHT",
              "MONSTER.SPECTRAL_KNIGHT",
              "MONSTER.MAGI_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 379,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 16,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ],
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 191,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 12,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 445,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SHADOW_STEP"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GAMMA_BLAST"
                },
                "was_picked": false
              }
            ],
            "current_gold": 426,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 47,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.TUNING_FORK",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLIGHT_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 211,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 45,
            "gold_lost": 25,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 73,
            "max_hp_gained": 7,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 42,
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BULLET_TIME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 42,
                "id": "CARD.SPEEDSTER"
              }
            ],
            "current_gold": 500,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 55,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.ETERNAL_FEATHER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 34,
                "id": "CARD.DOUBT"
              }
            ],
            "current_gold": 163,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 163,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SEVERANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MELANCHOLY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLEIGHT_OF_FLESH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JACK_OF_ALL_TRADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALAMITY"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 111,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": false
              },
              {
                "choice": "RELIC.BIG_HAT",
                "was_picked": false
              },
              {
                "choice": "RELIC.LEES_WAFFLE",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 43,
                  "id": "CARD.FLANKING"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 43,
                "id": "CARD.FLANKING"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 34,
                "id": "CARD.DOUBT"
              }
            ],
            "current_gold": 299,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 76,
            "gold_spent": 125,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 163,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DEFEND_REGENT"
            ]
          },
          {
            "current_gold": 111,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.UNLEASH"
            ]
          },
          {
            "current_gold": 299,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.FLANKING"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 163,
            "current_hp": 73,
            "damage_taken": 2,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_used": [
              "POTION.DEXTERITY_POTION",
              "POTION.POWER_POTION"
            ]
          },
          {
            "current_gold": 66,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 45,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_used": [
              "POTION.DEXTERITY_POTION",
              "POTION.ENERGY_POTION",
              "POTION.RADIANT_TINCTURE",
              "POTION.POTION_OF_DOOM",
              "POTION.POT_OF_GHOULS"
            ]
          },
          {
            "current_gold": 299,
            "current_hp": 61,
            "damage_taken": 3,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_used": [
              "POTION.STRENGTH_POTION",
              "POTION.SKILL_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.QUEEN_BOSS",
            "monster_ids": [
              "MONSTER.TORCH_HEAD_AMALGAM",
              "MONSTER.QUEEN"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.GAMMA_BLAST"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.GATHER_LIGHT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 14,
          "id": "CARD.HEGEMONY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.GENESIS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.RESONANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 22,
          "id": "CARD.SPECTRUM_SHIFT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 26,
          "id": "CARD.DEVASTATE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 29,
          "id": "CARD.ORBIT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 34,
          "id": "CARD.REFLECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 34,
          "id": "CARD.SUMMON_FORTH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 2
              },
              {
                "name": "TinkerTimeRider",
                "value": 5
              }
            ]
          }
        }
      ],
      "id": 76561199169575477,
      "max_potion_slot_count": 3,
      "potions": [
        {
          "id": "POTION.GAMBLERS_BREW",
          "slot_index": 2
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.PRECISE_SCISSORS"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.TINY_MAILBOX"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.THE_COURIER"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.YUMMY_COOKIE"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.LAVA_LAMP",
          "props": {
            "bools": [
              {
                "name": "TookDamageThisCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.TOXIC_EGG"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.HORN_CLEAT"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.AMETHYST_AUBERGINE"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.SAI"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.RED_MASK"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.TUNING_FORK",
          "props": {
            "ints": [
              {
                "name": "SkillsPlayed",
                "value": 3
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        }
      ]
    },
    {
      "character": "CHARACTER.NECROBINDER",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.BODYGUARD"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.UNLEASH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.REANIMATE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.BORROWED_TIME"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.GRAVE_WARDEN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.SEANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.SEANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.INVOKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 26,
          "id": "CARD.GRAVE_WARDEN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.DEVOUR_LIFE"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 3
              },
              {
                "name": "TinkerTimeRider",
                "value": 7
              }
            ]
          }
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 40,
          "id": "CARD.PARSE"
        }
      ],
      "id": 76561198237752388,
      "max_potion_slot_count": 5,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BOUND_PHYLACTERY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.ICE_CREAM"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.POTION_BELT"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.SEAL_OF_GOLD"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.LANTERN"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.CANDELABRA"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.DOLLYS_MIRROR"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.GREMLIN_HORN"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.BOWLER_HAT"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.SPIKED_GAUNTLETS"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.REPTILE_TRINKET"
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.REGAL_PILLOW"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.STRAWBERRY"
        }
      ]
    },
    {
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.RICOCHET"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.BACKFLIP"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.CLUMSY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 13,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.FAN_OF_KNIVES"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.TACTICIAN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.HAND_TRICK"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.BACKFLIP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.FOOTWORK"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.ESCAPE_PLAN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 22,
          "id": "CARD.ESCAPE_PLAN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.SHADOW_STEP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 29,
          "id": "CARD.ACROBATICS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.ADRENALINE"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.OUTBREAK"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.INFINITE_BLADES"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 2
              },
              {
                "name": "TinkerTimeRider",
                "value": 4
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.SPEEDSTER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 43,
          "id": "CARD.FLANKING"
        }
      ],
      "id": 76561198980444751,
      "max_potion_slot_count": 3,
      "potions": [
        {
          "id": "POTION.SWIFT_POTION",
          "slot_index": 0
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.PRECARIOUS_SHEARS"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.AMETHYST_AUBERGINE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.STURDY_CLAMP"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.HORN_CLEAT"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.YUMMY_COOKIE"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.ORRERY"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.CHANDELIER"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.UNCEASING_TOP"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.PLANISPHERE"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.IRON_CLUB",
          "props": {
            "ints": [
              {
                "name": "CardsPlayed",
                "value": 371
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.KUSARIGAMA"
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.RIPPLE_BASIN"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.ETERNAL_FEATHER"
        }
      ]
    }
  ],
  "run_time": 3452,
  "schema_version": 8,
  "seed": "4MZXC0T8QQ",
  "start_time": 1773022291,
  "was_abandoned": false,
  "win": true
}