{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 8,
  "build_id": "v0.98.3",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "LOST_COFFER",
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "LARGE_CAPSULE",
                "title": {
                  "key": "LARGE_CAPSULE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NEUTRON_AEGIS"
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.BEGONE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BEGONE"
              }
            ],
            "current_gold": 108,
            "current_hp": 50,
            "damage_taken": 10,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPECTRUM_SHIFT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPLASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAT_DOWN"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 33,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": false
              },
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": false
              },
              {
                "choice": "RELIC.DOLLYS_MIRROR",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SOLAR_STRIKE"
              }
            ],
            "current_gold": 44,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.LEAF_SLIME_S",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.TWIG_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 102,
            "current_hp": 50,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "JUNGLE_MAZE_ADVENTURE.pages.INITIAL.options.JOIN_FORCES.title",
                  "table": "events"
                },
                "variables": {
                  "SoloGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 147.381261,
                    "bool_value": false,
                    "string_value": null
                  },
                  "JoinForcesGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 58.21058,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 58,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.JUNGLE_MAZE_ADVENTURE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPECTRUM_SHIFT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 113,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 113,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SOLAR_STRIKE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.ORBIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ORBIT"
              }
            ],
            "current_gold": 123,
            "current_hp": 41,
            "damage_taken": 9,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FRUIT_JUICE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INKLETS_NORMAL",
            "monster_ids": [
              "MONSTER.INKLET",
              "MONSTER.INKLET",
              "MONSTER.INKLET"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 123,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BEGONE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 159,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.TUNING_FORK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUMMON_FORTH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.COSMIC_INDIFFERENCE"
              }
            ],
            "current_gold": 174,
            "current_hp": 35,
            "damage_taken": 6,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.RUBY_RAIDERS_NORMAL",
            "monster_ids": [
              "MONSTER.BRUTE_RUBY_RAIDER",
              "MONSTER.CROSSBOW_RUBY_RAIDER",
              "MONSTER.ASSASSIN_RUBY_RAIDER"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GATHER_LIGHT"
              }
            ],
            "current_gold": 184,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MAWLER_NORMAL",
            "monster_ids": [
              "MONSTER.MAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 184,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.TERRAFORMING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 215,
            "current_hp": 60,
            "damage_taken": 2,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 80,
            "max_hp_gained": 5,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FRUIT_JUICE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE"
            ],
            "room_type": "elite",
            "turns_taken": 10
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SUPERMASSIVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LUNAR_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 228,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.POTION_OF_BINDING"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CUBEX_CONSTRUCT_NORMAL",
            "monster_ids": [
              "MONSTER.CUBEX_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 228,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.NEUTRON_AEGIS"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.BIG_BANG"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.I_AM_INVINCIBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUARDS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BIG_BANG"
              }
            ],
            "current_gold": 303,
            "current_hp": 21,
            "damage_taken": 39,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CEREMONIAL_BEAST_BOSS",
            "monster_ids": [
              "MONSTER.CEREMONIAL_BEAST"
            ],
            "room_type": "boss",
            "turns_taken": 12
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "ELECTRIC_SHRYMP",
                "title": {
                  "key": "ELECTRIC_SHRYMP.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "DRIFTWOOD",
                "title": {
                  "key": "DRIFTWOOD.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOUCH_OF_OROBAS",
                "title": {
                  "key": "TOUCH_OF_OROBAS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 303,
            "current_hp": 68,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DRIFTWOOD.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 47,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.DRIFTWOOD",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.OROBAS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 318,
            "current_hp": 60,
            "damage_taken": 8,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.DEXTERITY_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_NECTAR"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STARDUST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRAMATIC_ENTRANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCRAWL"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 218,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": false
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": false
              },
              {
                "choice": "RELIC.ORANGE_DOUGH",
                "was_picked": false
              },
              {
                "choice": "RELIC.CAULDRON",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 353,
            "current_hp": 49,
            "damage_taken": 11,
            "event_choices": [
              {
                "title": {
                  "key": "COLOSSAL_FLOWER.pages.INITIAL.options.REACH_DEEPER_1.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "COLOSSAL_FLOWER.pages.REACH_DEEPER_1.options.REACH_DEEPER_2.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "COLOSSAL_FLOWER.pages.REACH_DEEPER_2.options.EXTRACT_INSTEAD.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 135,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.COLOSSAL_FLOWER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 353,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.ORNATE.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "笨拙"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LANTERN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.HIDDEN_GEM"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.KNOCKOUT_BLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.I_AM_INVINCIBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PARRY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ULTIMATE_DEFEND"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HIDDEN_GEM"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 59,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 294,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.KUSARIGAMA",
                "was_picked": false
              },
              {
                "choice": "RELIC.CHANDELIER",
                "was_picked": false
              },
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 59,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ORBIT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PROPHESIZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PARRY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 25,
                  "id": "CARD.MANIFEST_AUTHORITY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 8,
                "id": "CARD.ORBIT"
              },
              {
                "id": "CARD.MANIFEST_AUTHORITY"
              }
            ],
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 8,
                "id": "CARD.ORBIT"
              }
            ],
            "current_gold": 73,
            "current_hp": 43,
            "damage_taken": 6,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 109,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.QUASAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 123,
            "current_hp": 41,
            "damage_taken": 2,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MYTES_NORMAL",
            "monster_ids": [
              "MONSTER.MYTE",
              "MONSTER.MYTE"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 123,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.HIDDEN_GEM"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 29,
                  "id": "CARD.GLOW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PILLAR_OF_CREATION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLOW"
              }
            ],
            "current_gold": 130,
            "current_hp": 38,
            "damage_taken": 3,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVICOPTER_NORMAL",
            "monster_ids": [
              "MONSTER.OVICOPTER"
            ],
            "room_type": "monster",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPECTRUM_SHIFT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LUNAR_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GENESIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 140,
            "current_hp": 33,
            "damage_taken": 5,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CHOMPERS_NORMAL",
            "monster_ids": [
              "MONSTER.CHOMPER",
              "MONSTER.CHOMPER"
            ],
            "room_type": "monster",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 140,
            "current_hp": 33,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RANWID_THE_ELDER.pages.INITIAL.options.RELIC.title",
                  "table": "events"
                },
                "variables": {
                  "Potion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "能力药水"
                  },
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "百年积木"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BELLOWS",
                "was_picked": true
              },
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": true
              }
            ],
            "relics_removed": [
              "RELIC.CENTENNIAL_PUZZLE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.RANWID_THE_ELDER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 140,
            "current_hp": 33,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.MANIFEST_AUTHORITY"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.DECISIONS_DECISIONS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BOMBARDMENT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DYING_STAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DECISIONS_DECISIONS"
              }
            ],
            "current_gold": 215,
            "current_hp": 20,
            "damage_taken": 13,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ATTACK_POTION",
              "POTION.POWER_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KAISER_CRAB_BOSS",
            "monster_ids": [
              "MONSTER.CRUSHER",
              "MONSTER.ROCKET"
            ],
            "room_type": "boss",
            "turns_taken": 13
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "GLITTER",
                "title": {
                  "key": "GLITTER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "DELICATE_FROND",
                "title": {
                  "key": "DELICATE_FROND.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "DIAMOND_DIADEM",
                "title": {
                  "key": "DIAMOND_DIADEM.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 215,
            "current_hp": 68,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "GLITTER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 48,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.GLITTER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NONUPEIPE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.TERRAFORMING"
                },
                "was_picked": false
              }
            ],
            "current_gold": 223,
            "current_hp": 55,
            "damage_taken": 13,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 6,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SKILL_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 223,
            "current_hp": 55,
            "damage_taken": 0,
            "downgraded_cards": [
              "CARD.NEUTRON_AEGIS",
              "CARD.HIDDEN_GEM"
            ],
            "event_choices": [
              {
                "title": {
                  "key": "REFLECTIONS.pages.INITIAL.options.TOUCH_A_MIRROR.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "upgraded_cards": [
              "CARD.STRIKE_REGENT",
              "CARD.HIDDEN_GEM",
              "CARD.BIG_BANG",
              "CARD.VENERATE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.REFLECTIONS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 37,
                  "id": "CARD.CONVERGENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.CONVERGENCE"
              }
            ],
            "current_gold": 231,
            "current_hp": 30,
            "damage_taken": 25,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.FLEX_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.SUPERMASSIVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 38,
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.PARTICLE_WALL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.BLACK_HOLE"
              }
            ],
            "current_gold": 238,
            "current_hp": 20,
            "damage_taken": 10,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 4,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_NORMAL",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 238,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.SUPERMASSIVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 40,
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.ORBIT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.PHOTON_CUT"
              }
            ],
            "current_gold": 246,
            "current_hp": 41,
            "damage_taken": 15,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_LOST_AND_FORGOTTEN_NORMAL",
            "monster_ids": [
              "MONSTER.THE_LOST",
              "MONSTER.THE_FORGOTTEN"
            ],
            "room_type": "monster",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 278,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.RIPPLE_BASIN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEGEMONY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PARRY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FASTEN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SECRET_WEAPON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DECISIONS_DECISIONS"
              }
            ],
            "current_gold": 126,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 152,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BEATING_REMNANT",
                "was_picked": false
              },
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": false
              },
              {
                "choice": "RELIC.LAVA_LAMP",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 43,
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.HEAVENLY_DRILL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.DEVASTATE"
              }
            ],
            "current_gold": 141,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FAIRY_IN_A_BOTTLE",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.STABLE_SERUM"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GLOBE_HEAD_NORMAL",
            "monster_ids": [
              "MONSTER.GLOBE_HEAD"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONVERGENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUMMON_FORTH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ORBIT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ULTIMATE_DEFEND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOSTALGIA"
                },
                "was_picked": false
              }
            ],
            "current_gold": 141,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORNAMENTAL_FAN",
                "was_picked": false
              },
              {
                "choice": "RELIC.ETERNAL_FEATHER",
                "was_picked": false
              },
              {
                "choice": "RELIC.WING_CHARM",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 45,
                  "id": "CARD.STARDUST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.TERRAFORMING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.STARDUST"
              }
            ],
            "current_gold": 148,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMED_BERSERKER_NORMAL",
            "monster_ids": [
              "MONSTER.SLIMED_BERSERKER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "floor_added_to_deck": 40,
                "id": "CARD.PHOTON_CUT"
              }
            ],
            "current_gold": 148,
            "current_hp": 34,
            "damage_taken": 7,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.HOLD_ON_0.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "光子切割"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 5,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_0.options.HOLD_ON_1.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "光子切割"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 5,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "光子切割"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 5,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SLIPPERY_BRIDGE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 148,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 148,
            "current_hp": 21,
            "damage_taken": 34,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.POWER_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TEST_SUBJECT_BOSS",
            "monster_ids": [
              "MONSTER.TEST_SUBJECT"
            ],
            "room_type": "boss",
            "turns_taken": 10
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRON_AEGIS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.BEGONE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 4,
          "id": "CARD.SOLAR_STRIKE"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.COSMIC_INDIFFERENCE"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.GATHER_LIGHT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.BIG_BANG"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.CLUMSY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.HIDDEN_GEM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 25,
          "id": "CARD.ORBIT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 25,
          "id": "CARD.MANIFEST_AUTHORITY"
        },
        {
          "floor_added_to_deck": 29,
          "id": "CARD.GLOW"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.DECISIONS_DECISIONS"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 37,
          "id": "CARD.CONVERGENCE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 38,
          "id": "CARD.BLACK_HOLE"
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.DECISIONS_DECISIONS"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 43,
          "id": "CARD.DEVASTATE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 45,
          "id": "CARD.STARDUST"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.FAIRY_IN_A_BOTTLE",
          "slot_index": 0
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.TUNING_FORK",
          "props": {
            "ints": [
              {
                "name": "SkillsPlayed",
                "value": 4
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.DRIFTWOOD"
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.LANTERN"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.BOOK_OF_FIVE_RINGS",
          "props": {
            "ints": [
              {
                "name": "CardsAdded",
                "value": 8
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.BELLOWS"
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.HORN_CLEAT"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.GLITTER"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.RIPPLE_BASIN"
        }
      ]
    }
  ],
  "run_time": 4863,
  "schema_version": 8,
  "seed": "LEKN648L02",
  "start_time": 1773236325,
  "was_abandoned": false,
  "win": true
}