{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 8,
  "build_id": "v0.98.3",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "STONE_HUMIDIFIER",
                "title": {
                  "key": "STONE_HUMIDIFIER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SCROLL_BOXES",
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.IMPATIENCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PROLONG"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LEAD_PAPERWEIGHT",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.PREDATOR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PREDATOR"
              }
            ],
            "current_gold": 113,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 113,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DOORS_OF_LIGHT_AND_DARK.pages.INITIAL.options.DARK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DOORS_OF_LIGHT_AND_DARK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FLICK_FLACK"
              }
            ],
            "current_gold": 121,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NOXIOUS_FUMES"
              }
            ],
            "current_gold": 128,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.OUTBREAK"
              }
            ],
            "current_gold": 139,
            "current_hp": 53,
            "damage_taken": 3,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEWER_CLAM_NORMAL",
            "monster_ids": [
              "MONSTER.SEWER_CLAM"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 151,
            "current_hp": 49,
            "damage_taken": 4,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CULTISTS_NORMAL",
            "monster_ids": [
              "MONSTER.CALCIFIED_CULTIST",
              "MONSTER.DAMP_CULTIST"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.EQUILIBRIUM"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPOSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACCURACY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ETERNAL_ARMOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.EQUILIBRIUM"
              }
            ],
            "current_gold": 65,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 86,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              },
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SPARKLING_ROUGE",
                "was_picked": false
              },
              {
                "choice": "RELIC.SHOVEL",
                "was_picked": false
              },
              {
                "choice": "RELIC.BELT_BUCKLE",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              }
            ],
            "current_gold": 74,
            "current_hp": 40,
            "damage_taken": 9,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FOSSIL_STALKER_NORMAL",
            "monster_ids": [
              "MONSTER.FOSSIL_STALKER"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 107,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 107,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.NOXIOUS_FUMES"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 117,
            "current_hp": 38,
            "damage_taken": 2,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GREMLIN_MERC_NORMAL",
            "monster_ids": [
              "MONSTER.GREMLIN_MERC"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 117,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PROLONG"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BUBBLE_BUBBLE"
              }
            ],
            "current_gold": 124,
            "current_hp": 32,
            "damage_taken": 6,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TWO_TAILED_RATS_NORMAL",
            "monster_ids": [
              "MONSTER.TWO_TAILED_RAT",
              "MONSTER.TWO_TAILED_RAT",
              "MONSTER.TWO_TAILED_RAT"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 179,
            "current_hp": 32,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_TREASURY.pages.INITIAL.options.FIRST_CHEST.title",
                  "table": "events"
                },
                "variables": {
                  "SmallChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 55,
                    "bool_value": false,
                    "string_value": null
                  },
                  "LargeChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 314,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 55,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SUNKEN_TREASURY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 179,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.THE_HUNT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FAN_OF_KNIVES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASSASSINATE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.THE_HUNT"
              }
            ],
            "current_gold": 254,
            "current_hp": 38,
            "damage_taken": 15,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_FYSH_BOSS",
            "monster_ids": [
              "MONSTER.SOUL_FYSH"
            ],
            "room_type": "boss",
            "turns_taken": 11
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "STORYBOOK",
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PUMPKIN_CANDLE",
                "title": {
                  "key": "PUMPKIN_CANDLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BRIGHTEST_FLAME"
              }
            ],
            "current_gold": 254,
            "current_hp": 63,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 25,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.STORYBOOK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.BUBBLE_BUBBLE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.BUBBLE_BUBBLE"
              }
            ],
            "current_gold": 262,
            "current_hp": 56,
            "damage_taken": 7,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 2,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ACCURACY"
                },
                "was_picked": false
              }
            ],
            "current_gold": 273,
            "current_hp": 50,
            "damage_taken": 6,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FINISHER"
                },
                "was_picked": false
              }
            ],
            "current_gold": 285,
            "current_hp": 32,
            "damage_taken": 18,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 2,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.CLARITY",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MYTES_NORMAL",
            "monster_ids": [
              "MONSTER.MYTE",
              "MONSTER.MYTE"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              }
            ],
            "current_gold": 299,
            "current_hp": 12,
            "damage_taken": 20,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.HUNTER_KILLER_NORMAL",
            "monster_ids": [
              "MONSTER.HUNTER_KILLER"
            ],
            "room_type": "monster",
            "turns_taken": 9
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 299,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 24,
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.OUTBREAK"
              }
            ],
            "current_gold": 308,
            "current_hp": 30,
            "damage_taken": 1,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.SWIFT_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 308,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.EQUILIBRIUM"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 344,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 344,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UP_MY_SLEEVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEG_SWEEP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NOXIOUS_FUMES"
              }
            ],
            "current_gold": 359,
            "current_hp": 41,
            "damage_taken": 8,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DROPLET_OF_PRECOGNITION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.CLARITY"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVICOPTER_NORMAL",
            "monster_ids": [
              "MONSTER.OVICOPTER"
            ],
            "room_type": "monster",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.FAKE_HAPPY_FLOWER",
              "RELIC.FAKE_VENERABLE_TEA_SET"
            ],
            "current_gold": 247,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 112,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.FAKE_HAPPY_FLOWER",
                "was_picked": true
              },
              {
                "choice": "RELIC.FAKE_VENERABLE_TEA_SET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.FAKE_MERCHANT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 254,
            "current_hp": 26,
            "damage_taken": 15,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_NORMAL",
            "monster_ids": [
              "MONSTER.BOWLBUG_SILK",
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.PROWESS"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPOSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JACKPOT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PROWESS"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 93,
            "current_hp": 26,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 161,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": false
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LUCKY_FYSH",
                "was_picked": false
              },
              {
                "choice": "RELIC.MEAL_TICKET",
                "was_picked": false
              },
              {
                "choice": "RELIC.MINIATURE_TENT",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 93,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.AFTERIMAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BULLET_TIME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAND_FINALE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.AFTERIMAGE"
              }
            ],
            "current_gold": 168,
            "current_hp": 4,
            "damage_taken": 41,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE"
            ],
            "room_type": "boss",
            "turns_taken": 10
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "FUR_COAT",
                "title": {
                  "key": "FUR_COAT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GLITTER",
                "title": {
                  "key": "GLITTER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "DIAMOND_DIADEM",
                "title": {
                  "key": "DIAMOND_DIADEM.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 168,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "GLITTER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 48,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.GLITTER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NONUPEIPE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.ACCURACY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              }
            ],
            "current_gold": 183,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_used": [
              "POTION.DROPLET_OF_PRECOGNITION",
              "POTION.SWIFT_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 248,
            "current_hp": 46,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clumsy"
                  }
                }
              }
            ],
            "gold_gained": 65,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 3
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 8
                    }
                  ]
                }
              }
            ],
            "current_gold": 248,
            "current_hp": 46,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.POWER.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.CURIOUS.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TINKER_TIME",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 38,
                  "id": "CARD.LEG_SWEEP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.LEG_SWEEP"
              }
            ],
            "current_gold": 261,
            "current_hp": 36,
            "damage_taken": 10,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.NEUTRALIZE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.SURVIVOR"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.ASCENDERS_BANE"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 1,
                "id": "CARD.PROLONG"
              },
              {
                "floor_added_to_deck": 2,
                "id": "CARD.PREDATOR"
              },
              {
                "floor_added_to_deck": 4,
                "id": "CARD.FLICK_FLACK"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 5,
                "id": "CARD.NOXIOUS_FUMES"
              },
              {
                "floor_added_to_deck": 6,
                "id": "CARD.OUTBREAK"
              },
              {
                "floor_added_to_deck": 7,
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 8,
                "id": "CARD.EQUILIBRIUM"
              },
              {
                "floor_added_to_deck": 17,
                "id": "CARD.THE_HUNT"
              },
              {
                "floor_added_to_deck": 18,
                "id": "CARD.BRIGHTEST_FLAME"
              },
              {
                "floor_added_to_deck": 19,
                "id": "CARD.BUBBLE_BUBBLE"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 24,
                "id": "CARD.OUTBREAK"
              },
              {
                "floor_added_to_deck": 28,
                "id": "CARD.NOXIOUS_FUMES"
              },
              {
                "floor_added_to_deck": 31,
                "id": "CARD.PROWESS"
              },
              {
                "floor_added_to_deck": 33,
                "id": "CARD.AFTERIMAGE"
              },
              {
                "floor_added_to_deck": 37,
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 3
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 8
                    }
                  ]
                }
              },
              {
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "floor_added_to_deck": 38,
                "id": "CARD.LEG_SWEEP"
              },
              {
                "id": "CARD.BAD_LUCK"
              }
            ],
            "current_gold": 261,
            "current_hp": 36,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "REFLECTIONS.pages.INITIAL.options.SHATTER.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.REFLECTIONS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 261,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.MAD_SCIENCE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 297,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ORICHALCUM",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 297,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 43,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.PHANTOM_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 43,
                  "id": "CARD.AFTERIMAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.FINISHER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.PINPOINT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.AFTERIMAGE"
              }
            ],
            "current_gold": 310,
            "current_hp": 22,
            "damage_taken": 32,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.AXEBOTS_NORMAL",
            "monster_ids": [
              "MONSTER.AXEBOT",
              "MONSTER.AXEBOT"
            ],
            "room_type": "monster",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 44,
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.WELL_LAID_PLANS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.OUTBREAK"
              }
            ],
            "current_gold": 310,
            "current_hp": 22,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_FUTURE_OF_POTIONS.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Rarity": {
                    "type": "String",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "罕见"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_discarded": [
              "POTION.POWDERED_DEMISE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_FUTURE_OF_POTIONS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_potions": [
              "POTION.SKILL_POTION"
            ],
            "bought_relics": [
              "RELIC.STRAWBERRY"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFLEX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACCURACY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_BOMB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAND_OF_GREED"
                },
                "was_picked": false
              }
            ],
            "current_gold": 47,
            "current_hp": 29,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 263,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 69,
            "max_hp_gained": 7,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": true
              },
              {
                "choice": "RELIC.MERCURY_HOURGLASS",
                "was_picked": false
              },
              {
                "choice": "RELIC.LAVA_LAMP",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 80,
            "current_hp": 20,
            "damage_taken": 9,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_MEMORIES",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SKILL_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
            "monster_ids": [
              "MONSTER.MECHA_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 80,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 80,
            "current_hp": 9,
            "damage_taken": 31,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 4,
            "player_id": 1,
            "potion_used": [
              "POTION.VULNERABLE_POTION",
              "POTION.LIQUID_MEMORIES",
              "POTION.SKILL_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TEST_SUBJECT_BOSS",
            "monster_ids": [
              "MONSTER.TEST_SUBJECT"
            ],
            "room_type": "boss",
            "turns_taken": 16
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.PROLONG"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.PREDATOR"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.OUTBREAK"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 8,
          "id": "CARD.EQUILIBRIUM"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.THE_HUNT"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.BRIGHTEST_FLAME"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.BUBBLE_BUBBLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 24,
          "id": "CARD.OUTBREAK"
        },
        {
          "floor_added_to_deck": 28,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.PROWESS"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.AFTERIMAGE"
        },
        {
          "floor_added_to_deck": 37,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 3
              },
              {
                "name": "TinkerTimeRider",
                "value": 8
              }
            ]
          }
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 38,
          "id": "CARD.LEG_SWEEP"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.PROLONG"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.PREDATOR"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.OUTBREAK"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.EQUILIBRIUM"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.THE_HUNT"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.BRIGHTEST_FLAME"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.BUBBLE_BUBBLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.OUTBREAK"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.PROWESS"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.AFTERIMAGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 3
              },
              {
                "name": "TinkerTimeRider",
                "value": 8
              }
            ]
          }
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 39,
          "id": "CARD.LEG_SWEEP"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.BAD_LUCK"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 43,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 43,
          "id": "CARD.AFTERIMAGE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 44,
          "id": "CARD.OUTBREAK"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 4,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LEAD_PAPERWEIGHT"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.POTION_BELT"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.STORYBOOK"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.FAKE_HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 2
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.FAKE_VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.GLITTER"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.ORICHALCUM"
        },
        {
          "floor_added_to_deck": 45,
          "id": "RELIC.STRAWBERRY"
        },
        {
          "floor_added_to_deck": 46,
          "id": "RELIC.PERMAFROST"
        }
      ]
    }
  ],
  "run_time": 2556,
  "schema_version": 8,
  "seed": "UWL4X3CY3E",
  "start_time": 1773594688,
  "was_abandoned": false,
  "win": true
}